# Generated by Django 4.2.27 on 2026-01-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('operator_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='active', max_length=20)),
                ('opening_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('station', 'Station'), ('showroom', 'Showroom'), ('service', 'Service')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='StationAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(db_column='amenity_id', on_delete=django.db.models.deletion.CASCADE, to='stations.amenity')),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
            options={
                'db_table': 'station_amenities',
                'unique_together': {('station', 'amenity')},
            },
        ),
    ]
