# Generated by Django 4.2.27 on 2026-01-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charger',
            name='status',
        ),
    ]
