# Generated by Django 4.2.27 on 2026-01-13 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_remove_charger_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. CCS2, Type 2, CHAdeMO', max_length=100)),
                ('connector_type', models.CharField(help_text='Physical connector standard', max_length=50)),
                ('max_power_kw', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='charger',
            name='charger_type',
        ),
        migrations.RemoveField(
            model_name='charger',
            name='power_kw',
        ),
        migrations.RemoveField(
            model_name='charger',
            name='price_per_kwh',
        ),
        migrations.CreateModel(
            name='StationCharger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('end_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('charger_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_links', to='stations.chargertype')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_chargers', to='stations.station')),
            ],
            options={
                'unique_together': {('station', 'charger_type')},
            },
        ),
        migrations.AddField(
            model_name='charger',
            name='station_charger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='stations.stationcharger'),
        ),
    ]
