# Generated by Django 4.2.27 on 2026-01-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_amenity_category_stationamenity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationCharger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('end_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('charger_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_links', to='stations.chargertype')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_chargers', to='stations.station')),
            ],
            options={
                'unique_together': {('station', 'charger_type')},
            },
        ),
    ]
