# Generated by Django 4.2.27 on 2026-01-27 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0004_brand_showroom_showroomamenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='place',
            name='operator',
        ),
        migrations.AlterUniqueTogether(
            name='placecharger',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='placecharger',
            name='charger_type',
        ),
        migrations.RemoveField(
            model_name='placecharger',
            name='place',
        ),
        migrations.RemoveField(
            model_name='placeimage',
            name='place',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorite',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='stations.showroom'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='stations.station'),
        ),
        migrations.AlterField(
            model_name='chargertype',
            name='connector_type',
            field=models.CharField(help_text='e.g. Type 2, CCS2, CHAdeMO', max_length=100),
        ),
        migrations.AlterField(
            model_name='chargertype',
            name='max_power_kw',
            field=models.FloatField(help_text='Max power output in kW'),
        ),
        migrations.AlterField(
            model_name='chargertype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'station', 'showroom')},
        ),
        migrations.DeleteModel(
            name='Charger',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.DeleteModel(
            name='PlaceCharger',
        ),
        migrations.DeleteModel(
            name='PlaceImage',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='place',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
