# Generated by Django 4.2.27 on 2026-01-27 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0005_remove_place_amenities_remove_place_operator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('is_emergency_service', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('busy', 'Busy'), ('closed', 'Closed')], default='active', max_length=20)),
                ('opening_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorite',
            name='service_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='stations.servicecenter'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'station', 'showroom', 'service_center')},
        ),
        migrations.CreateModel(
            name='ServiceAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.amenity')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_amenities', to='stations.servicecenter')),
            ],
            options={
                'unique_together': {('service', 'amenity')},
            },
        ),
    ]
