# Generated by Django 4.2.27 on 2026-02-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_alter_address_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='physical_addresses',
        ),
        migrations.AlterModelTable(
            name='amenity',
            table='amenity_definitions',
        ),
        migrations.AlterModelTable(
            name='brand',
            table='vehicle_brands',
        ),
        migrations.AlterModelTable(
            name='chargertype',
            table='ev_charger_standards',
        ),
        migrations.AlterModelTable(
            name='favorite',
            table='user_favorites',
        ),
        migrations.AlterModelTable(
            name='serviceamenity',
            table='service_center_amenities',
        ),
        migrations.AlterModelTable(
            name='servicecenter',
            table='vehicle_service_centers',
        ),
        migrations.AlterModelTable(
            name='showroom',
            table='vehicle_showrooms',
        ),
        migrations.AlterModelTable(
            name='showroomamenity',
            table='showroom_amenity_mappings',
        ),
        migrations.AlterModelTable(
            name='station',
            table='charging_stations',
        ),
        migrations.AlterModelTable(
            name='stationamenity',
            table='charging_station_amenities',
        ),
        migrations.AlterModelTable(
            name='stationcharger',
            table='station_charging_points',
        ),
    ]
