# Generated by Django 4.2.27 on 2026-01-13 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_location_update',
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userlocation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
