# Generated by Django 4.2.27 on 2026-01-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_location_tracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
