# Generated by Django 4.2.27 on 2026-01-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_allow_location_tracking_user_is_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_app_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_charging_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_promotional_offers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_station_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
