# Generated by Django 4.2.27 on 2026-01-26 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_notify_app_updates_user_notify_charging_updates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allow_location_tracking',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_dark_mode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_app_updates',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_charging_updates',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_promotional_offers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_station_alerts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dark_mode', models.BooleanField(default=False)),
                ('allow_location_tracking', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_charging_updates', models.BooleanField(default=True)),
                ('notify_station_alerts', models.BooleanField(default=True)),
                ('notify_promotional_offers', models.BooleanField(default=False)),
                ('notify_app_updates', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
