# Generated by Django 4.2.27 on 2026-02-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_full_name_user_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='platform_users',
        ),
        migrations.AlterModelTable(
            name='userlocation',
            table='user_location_history',
        ),
        migrations.AlterModelTable(
            name='usernotificationsettings',
            table='user_notification_configs',
        ),
        migrations.AlterModelTable(
            name='userpreferences',
            table='user_app_preferences',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
